name: Проверка
on: [push]
jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/flake_requirements.txt
    - name: Flake8
      run: flake8 .
  container-job:
    name: Тесты
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
            POSTGRES_PASSWORD: 123
            POSTGRES_DBNAME: postgres
            POSTGRES_USER: app
            POSTGRES_PORT: 5432
            POSTGRES_HOST: 127.0.0.1
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.6"
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/test_requirements.txt
    - name: Тесты bash-curl
      run: |
        chmod +x tests/test.sh
        ./tests/test.sh
    - name: Тесты python-requests
      run: |
        pytest tests/test_requests.py